# FitGO - Configuraci\u00c3\u00b3n de la Aplicaci\u00c3\u00b3n

spring.application.name=FitGO

# BD - Configuraci\u00c3\u00b3n de la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/fitgo_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - JSON Web Token
# secret: clave de 256 bits para firmar los tokens
# expiration: duraci\u00c3\u00b3n en milisegundos (86400000 = 24 horas)
fitgo.jwt.secret=FitGO2025SecretKeyParaJWTMuySeguraYLarga256Bits!!
fitgo.jwt.expiration=86400000

# Servidor
server.port=8080
